# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

    # Main working host
  config.vm.define "ans" do |ans|
    ans.vm.box = "shekeriev/centos-stream-8"
    ans.vm.hostname = "ansible.do2.homework"
    ans.vm.network "private_network", ip: "192.168.150.110"
    ans.vm.provision "shell", path: "scripts/install-ansible-centos-stream.sh"
    ans.vm.provider :virtualbox do |vb|
      vb.name = "ANS"
      vb.memory = 2048
      vb.cpus = 1
    end
  end


  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/debian-11"
    web.vm.hostname = "web.do2.homework"
    web.vm.network "private_network", ip: "192.168.150.111"
    web.vm.network "forwarded_port", guest: 80, host: 8081
    web.vm.provider :virtualbox do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "WEB"
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
    end
  end
  
  # DB Vm Assignment #2
  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/centos-stream-8"
    db.vm.hostname = "db.do2.homework"
    db.vm.network "private_network", ip: "192.168.150.112"
    db.vm.provider :virtualbox do |vb|
      vb.name = "DB"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

end